/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo.grafos.documento;

/**
 *
 * @author Usuario
 */
public class Estaticos {

    public static String documento1 = "ISACA®\n"
            + "Con 95.000 asociados en 160 países, ISACA (www.isaca.org) es un líder global proveedor de conocimiento, certificaciones,\n"
            + "comunidad, promoción y educación sobre aseguramiento y seguridad de sistemas de información (SSII), gobierno empresarial\n"
            + "y gestión de TI y riesgo relacionado con TI y cumplimiento. Fundada en 1969, ISACA, independiente y sin ánimo de lucro,\n"
            + "celebra conferencias internaciones, publica el ISACA® Journal y desarrolla estándares internaciones de control y auditoría de\n"
            + "SSII, que ayudan a sus miembros a asegurar la confianza en, y aportar valor desde, los sistemas de información. También avanza\n"
            + "y avala habilidades y conocimientos en TI mediante los globalmente reconocidos certificados (CISA®) Certified Information\n"
            + "Systems Auditor®, (CISM®) Certified Information Security Manager®, (CGEIT®) Certified in the Governance of Enterprise IT®\n"
            + "y (CRISCTM) Certified in Risk and Information Systems Control TM. ISACA actualiza continuamente el COBIT®, el cuál ayuda\n"
            + "a los profesionales de TI y líderes de las organizaciones a llevar a cabo sus responsabilidades en la gestión y gobierno de TI,\n"
            + "particularmente en las áreas de aseguramiento, seguridad, riesgo y control y proporcionar valor al negocio.\n"
            + "Quality Statement:\n"
            + "This Work is translated into Spanish from the English language version of COBIT® 5 by the ISACA® Madrid Chapter\n"
            + "with the permission of ISACA®. The ISACA® Madrid Chapter assumes sole responsibility for the accuracy and\n"
            + "faithfulness of the translation.\n"
            + "Declaración de Calidad:\n"
            + "Este Trabajo ha sido traducido al español desde la versión en inglés de COBIT® 5 por el Capítulo de Madrid de ISACA® con\n"
            + "permiso de ISACA®. El capítulo de Madrid ISACA® asume responsabilidad única por la exactitud y la fidelidad de la traducción.\n"
            + "Copyright\n"
            + "© 2012 ISACA. All rights reserved. For usage guidelines, see www.isaca.org/COBITuse.\n"
            + "Derechos de autor\n"
            + "© 2012 ISACA. Todos los derechos reservados. Para pautas de uso, ver www.isaca.org/COBITuse.\n"
            + "Disclaimer:\n"
            + "ISACA has designed this publication, COBIT® 5 Enabling Processes (the ‘Work’), primarily as an educational resource for\n"
            + "governance of enterprise IT (GEIT), assurance, risk and security professionals. ISACA makes no claim that use of any of the Work\n"
            + "will assure a successful outcome. The Work should not be considered inclusive of all proper information, procedures and tests\n"
            + "or exclusive of other information, procedures and tests that are reasonably directed to obtaining the same results. In determining\n"
            + "the propriety of any specific information, procedure or test, readers should apply their own professional judgement to the specific\n"
            + "GEIT, assurance, risk and security circumstances presented by the particular systems or information technology environment.\n"
            + "Renuncia:\n"
            + "ISACA ha diseñado esta publicación, COBIT® 5 Procesos Catalizadores (el ‘Trabajo’), principalmente como una fuente\n"
            + "de educación para profesionales del gobierno de las TI empresariales (GEIT), del aseguramiento, del riesgo y de la\n"
            + "seguridad. ISACA no afirma que el uso de cualquier parte del Trabajo garantice un resultado exitoso. No debe considerarse\n"
            + "que el Trabajo incluya toda la información, procedimientos y pruebas correctas, ni que excluya otro tipo de información,\n"
            + "procedimientos y pruebas razonablemente dirigidos a obtener los mismos resultados. Al determinar la conveniencia de\n"
            + "cualquier información, procedimiento o prueba, el lector debe aplicar su propio juicio profesional a las circunstancias GEIT,\n"
            + "de aseguramiento, de riesgo o de seguridad específicos presentados por los sistemas particulares o ámbito de TI.\n"
            + "ISACA\n"
            + "3701 Algonquin Road, Suite 1010\n"
            + "Rolling Meadows, IL 60008 EE.UU.\n"
            + "Teléfono: +1.847.253.1545\n"
            + "Fax: +1.847.253.1443\n"
            + "E-mail: info@isaca.org\n"
            + "Página Web: www.isaca.org\n"
            + "Comentarios: www.isaca.org/cobit\n"
            + "Participar en el Centro de Conocimiento de ISACA: www.isaca.org/knowledge-center\n"
            + "Sigue a ISACA en Twitter: https://twitter.com/ISACANews\n"
            + "Únete a la conversación COBIT en Twitter: #COBIT\n"
            + "Únete a ISACA en LinkedIn: ISACA (Oficial), http://linkd.in/ISACAOfficial\n"
            + "Me gusta ISACA en Facebook: www.facebook.com/ISACAHQ\n"
            + "COBIT® 5: Procesos Catalizadores\n"
            + "ISBN 978-1-60420-285-4\n"
            + "Impreso en los Estados Unidos\n"
            + "Personal Copy of: Mr. Jorge Ivan Manrique Giraldo\n"
            + "3\n"
            + "Reconocimientos\n"
            + "Reconocimientos\n"
            + "ISACA quiere reconocer la labor:\n"
            + "Fuerza de trabajo de COBIT 5 (2009-2011)\n"
            + "John W. Lainhart, IV, CISA, CISM, CGEIT, IBM Global Business Services, EE.UU., Co-presidente\n"
            + "Derek J. Oliver, Ph.D., DBA, CISA, CISM, CRISC, CITP, FBCS, FISM, MInstISP,\n"
            + "Ravenswood Consultants Ltd., GB, Co-presidente\n"
            + "Pippa G. Andrews, CISA, ACA, CIA, KPMG, Australia\n"
            + "Elisabeth Judit Antonsson, CISM, Nordea Bank, Suecia\n"
            + "Steven A. Babb, CGEIT, CRISC, Betfair, GB\n"
            + "Steven De Haes, Ph.D., University of Antwerp Management School, Bélgica\n"
            + "Peter Harrison, CGEIT, FCPA, IBM Australia Ltd., Australia\n"
            + "Jimmy Heschl, CISA, CISM, CGEIT, ITIL Expert, bwin.party digital entertainment plc, Austria\n"
            + "Robert D. Johnson, CISA, CISM, CGEIT, CRISC, CISSP, Bank of America, EE.UU.\n"
            + "Erik H.J.M. Pols, CISA, CISM, Shell International-ITCI, Holanda\n"
            + "Vernon Richard Poole, CISM, CGEIT, Sapphire, GB\n"
            + "Abdul Rafeq, CISA, CGEIT, CIA, FCA, A. Rafeq and Associates, India\n"
            + "Equipo de Desarrollo\n"
            + "Floris Ampe, CISA, CGEIT, CIA, ISO 27000, PwC, Bélgica\n"
            + "Gert du Preez, CGEIT, PwC, Canadá\n"
            + "Stefanie Grijp, PwC, Bélgica\n"
            + "Gary Hardy, CGEIT, IT Winners, Sudáfrica\n"
            + "Bart Peeters, PwC, Bélgica\n"
            + "Dirk Steuperaert, CISA, CGEIT, CRISC, IT In Balance BVBA, Bélgica\n"
            + "Participantes de Talleres\n"
            + "Gary Baker, CGEIT, CA, Canadá\n"
            + "Brian Barnier, CGEIT, CRISC, ValueBridge Advisors, EE.UU.\n"
            + "Johannes Hendrik Botha, MBCS-CITP, FSM, GEIT Tright Skills Development, Sudáfrica\n"
            + "Ken Buechler, CGEIT, CRISC, PMP, Great-West Life, Canadá\n"
            + "Don Caniglia, CISA, CISM, CGEIT, FLMI, EE.UU.\n"
            + "Mark Chaplin, GB\n"
            + "Roger Debreceny, Ph.D., CGEIT, FCPA, University of Hawaii at Manoa, EE.UU.\n"
            + "Mike Donahue, CISA, CISM, CGEIT, CFE, CGFM, CICA, Towson University, EE.UU.\n"
            + "Urs Fischer, CISA, CRISC, CPA (Swiss), Fischer IT GRC Consulting & Training, Suiza\n"
            + "Bob Frelinger, CISA, CGEIT, Oracle Corporation, EE.UU.\n"
            + "James Golden, CISM, CGEIT, CRISC, CISSP, IBM, EE.UU.\n"
            + "Meenu Gupta, CISA, CISM, CBP, CIPP, CISSP, Mittal Technologies, EE.UU.\n"
            + "Gary Langham, CISA, CISM, CGEIT, CISSP, CPFA, Australia\n"
            + "Nicole Lanza, CGEIT, IBM, EE.UU.\n"
            + "Philip Le Grand, PRINCE2, Ideagen Plc, GB\n"
            + "Debra Mallette, CISA, CGEIT, CSSBB, Kaiser Permanente IT, EE.UU.\n"
            + "Stuart MacGregor, Real IRM Solutions (Pty) Ltd., Sudáfrica\n"
            + "Christian Nissen, CISM, CGEIT, FSM, CFN People, Dinamarca\n"
            + "Jamie Pasfield, ITIL V3, MSP, PRINCE2, Pfizer, GB\n"
            + "Eddy J. Schuermans, CGEIT, Esras bvba, Bélgica\n"
            + "Michael Semrau, RWE Germany, Alemania\n"
            + "Max Shanahan, CISA, CGEIT, FCPA, Max Shanahan & Associates, Australia\n"
            + "Alan Simmonds, TOGAF9, TCSA, PreterLex, GB\n"
            + "Cathie Skoog, CISM, CGEIT, CRISC, IBM, EE.UU.\n"
            + "Dejan Slokar, CISA, CGEIT, CISSP, Deloitte & Touche LLP, Canadá\n"
            + "Roger Southgate, CISA, CISM, GB\n"
            + "Nicky Tiesenga, CISA, CISM, CGEIT, CRISC, IBM, EE.UU.\n"
            + "Wim Van Grembergen, Ph.D., University of Antwerp Management School, Bélgica\n"
            + "Greet Volders, CGEIT, Voquals N.V., Bélgica\n"
            + "Christopher Wilken, CISA, CGEIT, PwC, EE.UU.\n"
            + "Tim M. Wright, CISA, CRISC, CBCI, GSEC, QSA, Kingston Smith Consulting LLP, GB";

    public static String documento2 = "Fase 2—Constituir un Equipo de Implementación Efectivo\n"
            + "Las dimensiones a considerar en el montaje de un equipo principal de implementación efectiva incluyen la participación\n"
            + "de las áreas apropiadas del negocio y de TI, así como el conocimiento y la pericia, la experiencia, la credibilidad y la\n"
            + "autoridad de los miembros del equipo. La obtención de una visión independiente y objetiva, conforme a lo dispuesto\n"
            + "por las partes externas, tales como consultores y un agente de cambio, también podría ser muy beneficioso al ayudar al\n"
            + "proceso de implementación o a la gestión de las carencias de aptitudes que puedan existir dentro de la empresa. Por lo\n"
            + "tanto, otra dimensión a considerar es la combinación adecuada de los recursos internos y externos.\n"
            + "La esencia del equipo debería ser un compromiso con:\n"
            + "• Una visión clara de éxito y metas ambiciosas\n"
            + "• Involucrar a los mejores de todos los miembros del equipo, todo el tiempo\n"
            + "• La claridad y la transparencia de los procesos del equipo, la rendición de cuentas y de las comunicaciones\n"
            + "• Integridad, el apoyo mutuo y el compromiso mutuo de éxito\n"
            + "• La responsabilidad mutua y responsabilidad colectiva\n"
            + "• Medición continua de su propio desempeño y la forma en que se comporta como un equipo\n"
            + "• Vivir fuera de su zona de confort, siempre buscando nuevas maneras de mejorar, descubrir nuevas posibilidades y\n"
            + "aceptar el cambio\n"
            + "Es importante identificar los posibles agentes de cambio dentro de las diferentes partes del negocio con las cuales el\n"
            + "equipo principal puede trabajar para apoyar la visión y la cascada de cambios.\n"
            + "Fase 3—Comunicar el Resultado Deseado\n"
            + "Debería desarrollarse un plan de habilitación del cambio a alto nivel en conjunto con el plan general del programa. Un\n"
            + "componente clave del plan de habilitación del cambio es la estrategia de comunicación, que debe ocuparse de quienes\n"
            + "serán los grupos principales de oyentes, sus perfiles de comportamiento y requisitos de información, sus canales de\n"
            + "comunicación y sus principios.\n"
            + "La visión deseada para el programa de implementación o mejora debe ser comunicada en el idioma de los afectados por\n"
            + "ella. La comunicación debería incluir los fundamentos y beneficios del cambio, así como los impactos de no realizar\n"
            + "el cambio (propósito), la visión (imagen), la hoja de ruta para lograr la visión (plan) y la participación necesaria de las\n"
            + "diferentes partes involucradas (partes).7 La alta dirección debería proporcionar mensajes clave (por ejemplo, la visión\n"
            + "deseada). Debería tenerse en cuenta en la comunicación que tanto los aspectos de comportamiento / cultural como lógicos\n"
            + "deberían ser abordados, y que el énfasis está en la comunicación de dos vías. Se deberían obtener reacciones, sugerencias\n"
            + "y otros comentarios y ser tomados en cuenta.\n"
            + "Fase 4—Potenciar a los Protagonistas e Identificar Resultados Rápidos\n"
            + "Según las principales mejoras se diseñan y construyen, se desarrollan los planes de respuesta al cambio para potenciar a\n"
            + "los diferentes protagonistas. El alcance de estos puede incluir:\n"
            + "• Cambios en el diseño organizativo, como por ejemplo, como el contenido del puesto o las estructuras de los equipos\n"
            + "• Los cambios operativos, tales como los flujos de procesos o de logística\n"
            + "• Cambios en la gestión de las personas, tales como la formación requerida y/o cambios en la gestión del rendimiento y\n"
            + "sistemas de recompensa\n"
            + "Todos los resultados rápidos que se puedan conseguir son importantes desde una perspectiva de habilitación del cambio.\n"
            + "Esto podría estar relacionado con los puntos débiles y eventos desencadenantes discutidos en el capítulo 3. Los resultados\n"
            + "7 Las ‘cuatro Ps’ (propósito, imagen (picture), plan y parte) es de Bridges, William; Managing Transitions: Making the Most of Change, Addison-Wesley,\n"
            + "EE.UU., 1999\n"
            + "Personal Copy of: Mr. Jorge Ivan Manrique Giraldo\n"
            + "38\n"
            + "Implementación\n"
            + "rápidos y visibles sin ambigüedades pueden crear un impulso y credibilidad para el programa y ayudar a hacer frente a\n"
            + "cualquier escepticismo que pueda existir.\n"
            + "Es imprescindible utilizar un enfoque participativo en el diseño y construcción de las mejoras principales. Al involucrar a\n"
            + "los afectados por el cambio en el diseño real, por ejemplo, a través de talleres y sesiones de evaluación, se puede aumentar\n"
            + "el compromiso\n"
            + "Fase 5—Habilitar la Operación y el Uso\n"
            + "Según se implementan las iniciativas dentro del ciclo de vida principal de implementación, también se aplican los planes\n"
            + "de respuesta al cambio. Los resultados rápidos que se han materializado se encuentran implantados y se han considerado\n"
            + "los aspectos conductuales y culturales generales de la transición (cuestiones tales como tratar con los temores de pérdida\n"
            + "de la responsabilidad, nuevas expectativas y tareas desconocidas).\n"
            + "Es importante equilibrar las intervenciones de grupo e individuales para aumentar la aceptación y el compromiso y para\n"
            + "garantizar que todas las partes involucradas obtengan una visión integral del cambio.\n"
            + "Las soluciones se pondrán en marcha, y durante este proceso, la orientación (mentoring) y el entrenamiento (coaching)\n"
            + "serán fundamentales para asegurar la captación en el entorno de usuario. Los requisitos y los objetivos de cambio que\n"
            + "habían sido establecidos durante el comienzo de la iniciativa deberían ser revisados para asegurarse de que hayan sido\n"
            + "tratados adecuadamente.\n"
            + "Deberían definirse medidas de éxito e incluirse tanto medidas de negocio como de percepción que permitan hacer un\n"
            + "seguimiento sobre lo que siente la gente acerca del cambio.\n"
            + "Fase 6—Incorporación de Nuevos Enfoques\n"
            + "A medida que se logran resultados concretos, las nuevas formas de trabajo deberían\n"
            + "convertirse en parte de la cultura de la empresa y estar basadas en sus normas\n"
            + "y valores (la forma en que hacemos las cosas aquí) mediante, por ejemplo, la\n"
            + "implementación de políticas, normas y procedimientos. Los cambios realizados\n"
            + "deberían ser controlados, y la eficacia de los planes de respuesta al cambio debería\n"
            + "evaluarse y tomar medidas correctivas, según corresponda. Esto podría incluir la\n"
            + "obligación de su cumplimiento, cuando así se requiera.\n"
            + "La estrategia de comunicación se debe mantener para mantener la concienciación en\n"
            + "curso.\n"
            + "Fase 7—Sostenimiento\n"
            + "Los cambios se mantienen a través del refuerzo consciente y una campaña de comunicación continua, y son mantenidos y\n"
            + "demostrados mediante el compromiso continuo de la alta dirección.\n"
            + "Se implementan planes de acción correctivos, se capturan las lecciones aprendidas y se comparte el conocimiento en todos los\n"
            + "sectores de la empresa.\n"
            + "Los cambios son sustentados\n"
            + "por las partes interesadas\n"
            + "mediante su ejemplo, a través\n"
            + "del refuerzo consciente y una\n"
            + "campaña de comunicación\n"
            + "continua.\n"
            + "Personal Copy of: Mr. Jorge Ivan Manrique Giraldo\n"
            + "Capítulo 6\n"
            + "Tareas, Roles y Responsabilidades en el Ciclo de Vida\n"
            + "de Implementación\n"
            + "39\n"
            + "Capítulo 6\n"
            + "Tareas, Roles y Responsabilidades en el Ciclo de Vida\n"
            + "de Implementación\n"
            + "Introducción\n"
            + "La mejora continua del GEIT se realiza utilizando las siete fases del ciclo de vida de implementación. Cada fase se\n"
            + "describe con:\n"
            + "• Un cuadro que resume las responsabilidades de cada grupo de protagonistas en la fase. Tenga en cuenta que estas\n"
            + "funciones son de carácter genérico y no necesariamente todos los roles deben existir como una función específica.\n"
            + "• Una tabla para cada fase que contiene:\n"
            + "– Objetivo de la Fase\n"
            + "– Descripción de la Fase\n"
            + "– Tareas de mejora continúa\n"
            + "– Tareas de habilitación del cambio\n"
            + "– Tareas de gestión del programa\n"
            + "– Ejemplos de las entradas que puedan ser necesarias\n"
            + "– Sugerencia de marcos de ISACA y de terceros que pueden ser utilizados\n"
            + "– Las salidas que necesitan ser producidas\n"
            + "• Una matriz RACI que describe quién es el responsable, quién rinde cuentas, quién es consultado e informado de las\n"
            + "actividades clave seleccionadas de la mejora continua (CI), de habilitación del cambio (CE) y las tareas de gestión del\n"
            + "programa (PM), con sus correspondientes referencias cruzadas. Las actividades incluidas en la matriz RACI son las\n"
            + "más importantes, por ejemplo, actividades que producen resultados o salidas a la siguiente fase, tienen un hito unido a\n"
            + "ellos, o son críticos para el éxito de la iniciativa global. No todas las actividades están incluidas, a efectos de mantener\n"
            + "esta guía concisa.\n"
            + "Esta guía no pretende ser prescriptiva,";
}
